<div class="container">
    <div class="row">
        What is Car Accident Law?
        Car accident law refers to the legal rules that determine who is responsible for the personal and property damage resulting from a traffic collision. This area of the law consists of the principles of negligence, as applied to this particular category of personal injury cases. Like other cases in which negligence law applies, car accident litigation is governed almost entirely by state law.
        While nuances exist, car accident victims in every state must prove the same basic four elements in order to recover compensation. These elements are: duty, breach, causation, and harm. With respect to duty, drivers have a legal obligation to obey the rules of the road and to operate their vehicles in a reasonable manner. This means driving a safe speed, maintaining control, exercising awareness, observing traffic signals, using blinkers and headlights, etc.
        The existence of a duty is typically accepted without much argument. By contrast, the plaintiff will usually be required to offer evidence that the defendant breached that duty. Breach can be shown by direct evidence, such as eyewitness testimony, traffic surveillance video, or an admission of fault. Or, the plaintiff may need to resort to circumstantial evidence, such as skid marks, paint smudges, or blood alcohol readings.
        Just because the defendant had a duty to operate his or her vehicle in a certain manner, and it is shown that the defendant breached that duty, the court will not assume those circumstances caused the plaintiff's injuries. Rather, the plaintiff must prove the element of causation. In car accident cases, this can be done through medical testimony demonstrating the injuries are consistent with the nature of the crash, and that they did not exist beforehand.
        Finally, the plaintiff must prove harm. No matter how egregious the other driver's conduct was behind the wheel, the plaintiff cannot bring a negligence lawsuit unless the conduct produced damage to the plaintiff's person or vehicle. "Near miss" cases will not qualify. Once harm is shown, the plaintiff may be entitled to compensation for medical expenses, pain and grief, lost wages, and more.
    </div>
</div>